name: azure github actions

env:
  MAVEN_VERSION: 3.8.2
  JAVA_VERSION: 21

on:
  push:
    branches:
      - master

jobs:
  building-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}   # Todo Make It '21'
          distribution: 'temurin' # 'adopt'
          architecture: x64
          cache: 'maven' # Strongly recommended for faster builds!
          cache-dependency-path: 'pom.xml' # Or '**/pom.xml' for multi-module projects

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: ${{ env.MAVEN_VERSION }} #3.8.2

      - name: Maven Validate
        run: mvn validate

      - name: Maven Package
        run: mvn package

      - name: Maven clean install
        run: mvn clean install