name: azure github actions

env:
  MAVEN_VERSION: 3.8.2
on:
  push:
    branches:
      - master

jobs:
  building-and-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
      - uses: actions/checkout@v5
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: ${{ env.MAVEN_VERSION }} #3.8.2

      - name: Maven Validate
        run: mvn validate

      - name: Maven Package
        run: mvn package

      - name: Maven clean install
        run: mvn clean install